CBL/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('browse/', include('browse.urls')),
    path('dnd/', include('dnd.urls')),
    path('terrarium/', include('terrarium.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm



app_name = 'browse'

urlpatterns = [
    path('', views.index, name='index'),
    path('shangri-la/',views.garden,name='shangri-la'),
    path('<int:pk>/', views.image, name='images'),
    path('thermo/',views.thermo, name='thermo'),
    path('santa/',views.santa, name='santas'),
    path('ticket/', views.gift, name='gifts'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='browse/login.html',authentication_form=LoginForm), name='login'),
]

dnd/urls.py
from django.urls import path, include

from . import views

app_name = 'dnd'

urlpatterns = [
    path('npcs/', views.NPC, name='npcs'),
    path('characters/', views.Character, name='characters'),
    path('spell_list/', views.spell_list, name='spells'),
    path('npcs/<int:pk>/', views.detail, name='detail'),
    path('dm/', views.dm_items, name='dm_items'),
    path('monsters/', views.monster, name='monsters'),
    path('maps/', views.maps, name='maps'),
    path('area/<int:pk>/', views.area, name='areas'),
    path('characters/<int:pk>/', views.character_detail, name='character_detail'),
    path('spells/<int:pk>/', views.spell_description, name='spell_description'),
    path('special_items/', views.special_items_list, name='items'),
    path('item/<int:pk>/', views.special_items, name='special_items'),
    path('shop/<int:pk>/', views.shopper, name='shoppers'),
    path('characters/<int:pk>/edit/', views.character_edit, name='edit'),
    path('shops/',views.special_shops, name='shops'),


]

dnd/forms.py
from django import forms

from .models import NonPlayerCharacter, Character_Sheet

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class NewCharacterForm(forms.ModelForm):
    class Meta:
        model = NonPlayerCharacter
        fields = ('name', 'race','affiliation','height', 'age', 'description', 'image',)

        widgets = {
            'name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'title': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'age': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'height': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'affiliation': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'race': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),

            'description': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),
            'image': forms.FileInput(attrs={
                'class': INPUT_CLASSES
            }),
        }

class CharacterSheet(forms.ModelForm):
    class Meta:
        model = Character_Sheet
        fields = ('character_name','lvl','hp','str','dex','con','int','wis','cha','ac','speed','special_item','special_item2','special_item3','special_item4','special_item5','special_item6','special_item7','spell','spell2','spell3','spell4','spell5','spell6','spell7')

        widgets = {
            'character_name': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'inspiration': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'hp': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'str': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'dex': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'con': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'int': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'wis': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'cha': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ac': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'speed': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'spell': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'spell2': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'spell3': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'spell4': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'spell5': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'spell6': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'spell7': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),

            'special_items': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'special_items2': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'special_items3': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'special_items4': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'special_items5': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'special_items6': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'special_items7': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

dnd/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, redirect
from .models import NonPlayerCharacter, Affiliation, Character_Sheet,Skill_Class, Weapon, Skill, Race, Spell, DM_Menu, Map, Monster,Special_Item,Shop
from .forms import NewCharacterForm, CharacterSheet


def detail(request, pk):
    npcs = get_object_or_404(NonPlayerCharacter, pk=pk)

    return render(request, 'dnd/detail.html', {
        'npcs': npcs,

    })
def NPC(request):
    #query = request.Get.get('query', npcs.affiliation)
    #affiliation_id = request.GET('affiliation', 0)
    npcs = NonPlayerCharacter.objects.filter(invisible=False)
    affiliation = Affiliation.objects.all()

    #if category_id:
        #projects = projects.filter(category_id=category_id)
    #if query:
        #projects = projects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'dnd/npcs.html', {
        'npcs': npcs,
        #'query':query,
        'affiliation':affiliation,
        #'affiliation_id': int(affiliation_id)
    })


def Character(request):

    characters = Character_Sheet.objects.filter(invisible=False)
    skill_class = Skill_Class.objects.all()
    skill = Skill.objects.all()
    race = Race.objects.all()
    weapon = Weapon.objects.all()
    spells = Spell.objects.all()

    return render(request, 'dnd/characters.html', {
        'characters':characters,
        'skill_class':skill_class,
        'skill':skill,
        'race':race,
        'weapon':weapon,
        'spells':spells,
    })

def character_detail(request, pk):
    characters = get_object_or_404(Character_Sheet, pk=pk)


    return render(request, 'dnd/character_detail.html', {
        'characters': characters,

    })

def spell_list(request):
    spells = Spell.objects.all()

    return render(request, 'dnd/spell_list.html', {
        'spells':spells,
    })

def spell_description(request, pk):
    spells = get_object_or_404(Spell, pk=pk)


    return render(request, 'dnd/spell_description.html', {
        'spells': spells,

    })

def dm_items(request):
    dm_items = DM_Menu.objects.all()

    return render(request, 'dnd/dm.html', {
        'dm_items':dm_items
    })

def maps(request):
    maps = Map.objects.all()

    return render(request, 'dnd/maps.html', {
        'maps':maps
    })
def area(request, pk):
    areas = get_object_or_404(Map, pk=pk)

    return render(request, 'dnd/area.html', {
        'areas': areas,

    })

def monster(request):
    monsters = Monster.objects.all()

    return render(request, 'dnd/monsters.html', {
        'monsters':monsters
    })


def special_items_list(request):
    items = Special_Item.objects.all()

    return render(request, 'dnd/special_items.html', {
        'items':items,
    })

def special_items(request, pk):
    special_items = get_object_or_404(Special_Item, pk=pk)

    return render(request, 'dnd/item.html', {
        'special_items': special_items,

    })

def special_shops(request):
    shops = Shop.objects.all()

    return render(request, 'dnd/shops.html',{
        'shops':shops
    })

def shopper(request,pk):
    shoppers = get_object_or_404(Shop,pk=pk)
    items = Special_Item.objects.all()

    return render(request, 'dnd/shop.html',{
        'shoppers':shoppers,

    })

@login_required
def character_edit(request, pk):
    character = get_object_or_404(Character_Sheet, pk=pk)

    if request.method == 'POST':
        form = CharacterSheet(request.POST, request.FILES, instance=character)

        if form.is_valid():
            character = form.save(commit=False)
            character.save()

            return redirect('dnd:characters')

    else:
        form = CharacterSheet(instance=character)

    return render(request, 'dnd/form.html', {
        'form': form,
        'title': 'Edit Character'
    })

dnd/templates/dnd/character_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ characters.name }}{% endblock %}

{% block content %}

    <div class="p-3 bg-gray-900 rounded-xl mb-4">
        <div class=" grid grid-cols-1 gap-4">
        <h1 class="pl-2 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 hover:text-yellow-700">{{ characters.name }}</h1></a>
        </div>

        <div class="text-xs sm:text-md lg:text-lg xl:text-xl text-center bg-gray-900 grid grid-cols-3 rounded-xl">
               <strong class="p-1 bg-gray-900 rounded-xl text-white">{{ characters.character_name }}</strong>
               <strong class="p-1 bg-gray-900 rounded-xl text-white">{{ characters.race }}</strong>
               <strong class="p-1 bg-gray-900 rounded-xl text-white">{{ characters.skill_class }}</strong>
        </div>

        <div class="grid grid-cols-1 "><img src="{{ characters.image.url }}" class="cols-span-1 mb-2 rounded-xl"></div>


        <strong class="text-yellow-800">Stats:</strong><br>
        <div class="px-3 text-xs sm:text-md lg:text-lg xl:text-xl text-center mb-2 mt-2 bg-gray-900 rounded-xl">
               <strong class="bg-black rounded-xl text-yellow-600 pl-6">Level:<span class="p-2 text-white"> {{ characters.lvl }} </span></strong><br>
               <strong class="bg-black rounded-xl text-yellow-600 pl-6">HP:<span class="p-2 text-white rounded-xl"> {{ characters.hp }} </span></strong>
               <strong class="bg-black rounded-xl text-yellow-600 pl-6">AC:<span class="p-2 text-white"> {{ characters.ac }} </span></strong>
        </div>

        <div class=" cols-span-3">

            <div class="text-xs sm:text-md lg:text-lg xl:text-xl text-center mb-2 p-3 justify-center items-center bg-gray-700 rounded-xl col-span-1">

               <strong class="pl-4 text-yellow-200">Strength:<span class="p-2 text-white">{{ characters.str }} </span></strong>
               <strong class="pl-4 text-yellow-200">Dexterity<span class="p-2 text-white">{{ characters.dex }} </span></strong>
               <strong class="pl-4 text-yellow-200">Constitution:<span class="p-2 text-white"> {{ characters.con }} </span></strong>
               <strong class="pl-4 text-yellow-200">Intelligence:<span class="p-2 text-white"> {{ characters.int }} </span></strong>
               <strong class="pl-4 text-yellow-200">Wisdom:<span class="p-2 text-white"> {{ characters.wis }} </span></strong>
               <strong class="pl-4 text-yellow-200">Charisma:<span class="p-2 text-white"> {{ characters.cha }} </span></strong>

            </div>
            <div class="text-xs sm:text-md lg:text-lg xl:text-xl text-center justify-center grid grid-cols-2">

             <div class="text-xs sm:text-md lg:text-lg xl:text-xl text-center justify-center rounded-xl">
            <div class="p-3 bg-gray-700 pl-6 col-span-1 rounded-xl">
                <strong class=" text-yellow-500">Proficient Skills:</strong><br>
                {% if characters.proficient_skill %}
                <h1 class="text-white"> {{ characters.proficient_skill }}</h1>
                {% endif %}
                {% if characters.skill_2 %}
                <h1 class="text-white"> {{ characters.skill_2 }}</h1>
                {% endif %}
                {% if characters.skill_3 %}
                <h1 class="text-white"> {{ characters.skill_3 }}</h1>
                {% endif %}
                {% if characters.skill_4 %}
                <h1 class="text-white"> {{ characters.skill_4 }}</h1>
                {% endif %}
                {% if characters.skill_5 %}
                <h1 class="text-white"> {{ characters.skill_5 }}</h1>
                {% endif %}
                {% if characters.skill_6 %}
                <h1 class="text-white"> {{ characters.skill_6 }}</h1>
                {% endif %}
                {% if characters.skill_7 %}
                <h1 class="text-white"> {{ characters.skill_7 }}</h1>
                {% endif %}
                {% if characters.skill_8 %}
                <h1 class="text-white"> {{ characters.skill_8 }}</h1>
                {% endif %}

            </div>
                </div>

            <div class="pl-3 text-xs sm:text-md lg:text-lg xl:text-xl text-center justify-center rounded-xl">
            <div class="p-3 bg-gray-700 col-span-1 rounded-xl">
                <strong class="text-yellow-500">Spells & Abilities:</strong><br>
                {% if characters.spell %}
                <a href="{{ characters.spell_link }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell }}</h1>
                </a>
                {% endif %}
                {% if characters.spell2 %}
                <a href="{{ characters.spell_link2 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell2 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell3 %}
                <a href="{{ characters.spell_link3 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell3 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell4 %}
                <a href="{{ characters.spell_link4 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell4 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell5 %}
                <a href="{{ characters.spell_link5 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell5 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell6 %}
                <a href="{{ characters.spell_link6 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell6 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell7 %}
                <a href="{{ characters.spell_link7 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell7 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell8 %}
                <a href="{{ characters.spell_link8 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell8 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell9 %}
                <a href="{{ characters.spell_link9 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell9 }}</h1>
                </a>
                {% endif %}
                {% if characters.spell10 %}
                <a href="{{ characters.spell_link10 }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.spell10 }}</h1>
                </a>
                {% endif %}

            </div>

                </div>
            </div>
        </div>

    </div>

    <div class="mb-3 grid grid-cols-1 gap-2">



            <div class="bg-gray-900 rounded-xl">
                <div class=" grid grid-cols-1 gap-4">
            <strong class="pl-2 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 ">Weapons</strong>
            </div>
            <div class="grid grid-cols-3 items-center">

            <div class="mb-4 text-xs sm:text-md lg:text-lg xl:text-xl text-center bg-gray-900 grid grid-cols-1 rounded-xl">
               <strong class="text-white"> {{ characters.weapon }} </strong>
               <strong class="text-yellow-500">Damage<span class="text-white"> {{ characters.weapon.damage }} </span></strong>
               <strong class="text-yellow-500">Bonus <span class="text-white"> {{ characters.weapon_bonus }} </span></strong>

                </div>

            {% if characters.weapon_2 %}
            <div class="grid grid-cols-1">

            <div class="mb-4 text-xs sm:text-md lg:text-lg xl:text-xl text-center bg-gray-900 grid grid-cols-1  rounded-xl">
               <strong class="text-white"> {{ characters.weapon_2 }} </strong>
               <strong class="text-yellow-500">Damage<span class="text-white"> {{ characters.weapon_2.damage }} </span></strong>
               <strong class="text-yellow-500">Bonus <span class="text-white"> {{ characters.weapon2_bonus }} </span></strong>
            </div>

                </div>
                {% endif %}

            {% if characters.weapon_3 %}
            <div class="grid grid-cols-1">

            <div class="mb-4 pl-1 text-xs sm:text-md lg:text-lg xl:text-xl text-center bg-gray-900 grid grid-cols-1 rounded-xl">
               <strong class="text-white"> {{ characters.weapon_3 }} </strong>
               <strong class="text-yellow-500">Damage<span class="text-white"> {{ characters.weapon_3.damage }} </span></strong>
               <strong class="text-yellow-500">Bonus <span class="text-white"> {{ characters.weapon3_bonus }} </span></strong>
            </div>

                </div>
                {% endif %}
            </div>
            </div>
            </div>

    <div class="p-6 rounded-xl bg-gray-700 mb-2">
        <div class=" grid grid-cols-1 gap-4">
        <strong class="pl-2 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 ">Equipment</strong>
        </div>
        <div class="grid grid-cols-1 p-3">
            <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-white">{{ characters.equipment }}</h2>
            </div>
        </div>
    </div>

    <div class="p-6 bg-gray-900 rounded-xl mb-20">
        <div class=" grid grid-cols-1 gap-4">
        <strong class="pl-2 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 ">Special Items:</strong>
        </div>
        <div class=" grid grid-cols-1 p-3">
            {% if characters.special_item %}
                <a href="{{ characters.special_item.link }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.special_item }}</h1>
                </a>
                {% endif %}
                {% if characters.special_item2 %}
                <a href="{{ characters.special_item2.link }}">
                <h1 class="text-white hover:text-yellow-600"> {{ characters.special_item2 }}</h1>
                </a>
                {% endif %}
            </div>
        </div>
    </div>

{% if authenticated %}
    <div class="p-6 bg-black rounded-xl mb-20 ">
        <div class=" pl-28 grid grid-cols-1 gap-4 items-center">
        <a href="{% url 'dnd:edit' characters.id %}" >
        <button class="w-4/5 mt-3 py-4 px-8 text-lg text-white bg-red-700 hover:bg-red-900 rounded-xl">Edit</button>
        </a>
        </div>

        </div>
{% endif %}




{% endblock %}

dnd/templates/dnd/characters.html
{% extends 'core/base.html' %}

{% block title %}Characters Sheets{% endblock %}
{% block content %}


    <div class="mt-2 mb-20 px-3 py-12 bg-black rounded-xl">

        <div class="grid grid-cols-2 gap-3">
            {% for character in characters %}
            <div>
                <a href="{% url 'dnd:character_detail' character.id %}">
                    <div>
                        <img src="{{ character.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-3 bg-green-900 rounded-b-xl">

                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ character.name }}

                        </h2>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

dnd/templates/dnd/dm.html
{% extends 'core/base.html' %}

{% block title %}DM Menu{% endblock %}
{% block content %}

<div class="mt-6 px-6 py-4 bg-black rounded-xl">
        <h2 class="mb-6 text-2xl text-center text-yellow-500">Menu</h2>

        <div class="mb-20 grid grid-cols-1 gap-3">
            {% for dm_item in dm_items %}
            <div>
                    <div class="p-12 bg-green-900 hover:bg-green-700 rounded-xl">
                        <a href="{{ dm_item.link }}">
                            <h2 class="text-2xl text-center text-white hover:text-yellow-700">{{ dm_item.name }}</h2>

                        </a>

                    </div>

            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

dnd/templates/dnd/npcs.html
{% extends 'core/base.html' %}

{% block title %}Non Player Characters{% endblock %}
{% block content %}
    <div class="grid grid-cols-6">
        {% for affiliation in affiliations %}
                <h1 class="mb-6 px-2 text-xs sm:text-sm lg:text-lg xl:text-xl text-center text-white hover:text-yellow-900{% if category.id == category_id %} text-yellow-500{% endif %}">
                    <a href="{% url 'browse:index' %}?query={{ query }}&affiliation={{ affiliation.id }}">{{ affiliation.name }}</a>
                </h1>

        {% endfor %}
    </div>

    <div class="mt-2 mb-20 px-3 py-12 bg-black-rounded-xl">

        <div class="grid grid-cols-2 gap-3">
            {% for npc in npcs %}
            <div>
                <a href="{% url 'dnd:detail' npc.id %}">
                    <div>
                        <img src="{{ npc.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-3 bg-green-900 rounded-b-xl">

                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ npc.name }}

                        </h2>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

dnd/templates/dnd/shop.html
{% extends 'core/base.html' %}

{% block title %}{{ shoppers.name }}{% endblock %}
{% block content %}


    <div class="mb-20 px-3 bg-black rounded-xl">

        <div class="grid grid-cols-2 gap-3">
                    <div class="col-span-2 p-3 bg-green-900 rounded-t-xl mb-4">
                        <h2 class=" text-center p-4 text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white rounded-xl">{{ shoppers.name }}
                        </h2>

                    </div>
            </div>


                    <div>
                        <img src="{{ shoppers.image.url }}" class="object-contain rounded-xl">
                    </div>
                <div class="grid grid-cols-3 gap-3 p-3 mt-3 ">
                     <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item1.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item1.name }}
                        </h2>
                        </a>
                    </div>
                    <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item2.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item2.name }}
                        </h2>
                        </a>
                    </div>
                    <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item3.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item3.name }}
                        </h2>
                        </a>
                    </div>
                    <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item4.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item4.name }}
                        </h2>
                        </a>
                    </div>
                    <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item5.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item5.name }}
                        </h2>
                        </a>
                    </div>
                    <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item6.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item6.name }}
                        </h2>
                        </a>
                    </div>
                    <div class="col-span-1 p-3 bg-green-900 rounded-xl text-center">
                         <a href="{% url 'dnd:special_items' shoppers.item7.id %}">
                        <h2 class=" text-xs sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ shoppers.item7.name }}
                        </h2>
                        </a>
                    </div>

        </div>

        </div>
    </div>

{% endblock %}

dnd/templates/dnd/shops.html
{% extends 'core/base.html' %}

{% block title %}Shops{% endblock %}

{% block content %}

        <div class="grid grid-cols-2 gap-3 p-6 mb-20">
            {% for shop in shops %}
            <div>
                    <a href="{% url 'dnd:shoppers' shop.id %}">
                    <div>
                        <h2 class="p-6 text-sm sm:text-sm lg:text-lg xl:text-xl text-white hover:text-yellow-500 bg-green-700 rounded-xl">{{ shop.name }}</h2>
                    </div>
                    </a>
            </div>
            {% endfor %}
        </div>


{% endblock %}

dnd/templates/dnd/special_items.html
{% extends 'core/base.html' %}

{% block title %}Special Items{% endblock %}

{% block content %}

        <div class="grid grid-cols-2 gap-3 p-6 mb-20">
            {% for item in items %}
            <div>
                <a href="{% url 'dnd:special_items' item.id %}">
                    <div>
                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ item.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>


{% endblock %}

dnd/templates/dnd/spell_list.html
{% extends 'core/base.html' %}

{% block title %}Spells & Abilities{% endblock %}

{% block content %}

        <div class="grid grid-cols-2 gap-3 p-6 mb-20">
            {% for spell in spells %}
            <div>
                <a href="{% url 'dnd:spell_description' spell.id %}">
                    <div>
                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ spell.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>


{% endblock %}