CBL/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('browse/', include('browse.urls')),
    path('dnd/', include('dnd.urls')),
    path('terrarium/', include('terrarium.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm



app_name = 'browse'

urlpatterns = [
    path('', views.index, name='index'),
    path('shangri-la/',views.garden,name='shangri-la'),
    path('<int:pk>/', views.image, name='images'),
    path('thermo/',views.thermo, name='thermo'),
    path('santa/',views.santa, name='santas'),
    path('ticket/', views.gift, name='gifts'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='browse/login.html',authentication_form=LoginForm), name='login'),
]

core/urls.py
from django.urls import path, include

from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('services/', views.services, name='services'),
    path('browse/', include('browse.urls')),
    path('commission/', views.commission, name='commission'),
    path('menu/', views.menu_items, name='menu'),
    path('roll/',views.roll, name='roll'),
]

projects/urls.py
from django.urls import path, include

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('browse/', include('browse.urls')),
    path('new/', views.new, name='new'),
    path('<int:pk>/images/', views.images, name='images'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/enchance/', views.enhance, name='enhance'),
]

terrarium/urls.py
from django.urls import path, include

from . import views

app_name = 'terrarium'

urlpatterns = [
    path('terrarium/', views.terrariums, name='terrariums'),
    path('terrarium/<int:pk>/', views.detail, name='detail'),
    path('plant/<int:pk>/', views.plant_detail, name='plant'),
    path('plants/',views.plants, name='plants')

]

core/models.py
from django.db import models

core/forms.py
from django import forms

from projects.models import Category, Project, Service, ServiceRequest


INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'


class ServiceForm(forms.ModelForm):
    class Meta:
        model = ServiceRequest
        fields = ('subject','email', 'message')

        widgets = {
            'subject': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),

            'email': forms.EmailInput(attrs={
                'class': INPUT_CLASSES
            }),
            'message': forms.Textarea(attrs={
                'class': INPUT_CLASSES
            }),

        }

core/views.py
from django.shortcuts import render,redirect
from django.template.loader import render_to_string
from django.core.mail import send_mail
from django.conf import settings
import random

from projects.models import Category, Project, Service, ServiceRequest, Menu_item, About

from .forms import ServiceForm

def index(request):
    projects = Project.objects.filter(front_page=True)[0:2]
    categories = Category.objects.all()

    return render(request, 'core/index.html', {
        'categories': categories,
        'projects': projects,
    })

def commission(request):
    services = Service.objects.all()


    return render(request, 'core/commission.html', {
        'services': services
    })
def menu_items(request):
    menu_items = Menu_item.objects.all()


    return render(request, 'core/menu.html', {
        'menu_items': menu_items
    })
def services(request):
    if request.method == 'POST':
        form = ServiceForm(request.POST)

        if form.is_valid():
            subject = form.cleaned_data['subject']
            message = form.cleaned_data['message']
            email = form.cleaned_data['email']
            html = render_to_string('core/servicerequest.html',{
                'email' : email,
                'message': message,
                'subject': subject
            })
            send_mail(subject,message,email,['circuitboredlab@gmail.com'],html_message=html)
            return redirect('/')
        else:
            print('is not valid')
            form = ServiceForm()
        message_subject = request.POST['message-subject']
        message_email = request.POST['message-email']
        message = request.POST['message']

        send_mail(
            subject,# subject
            message, #message
            message_email, #from email
            ['circuitboredlab@gmail.com'], #To email
        )
    form = ServiceForm()

    return render(request, 'core/services.html',{
        'form':form,
    })

def about(request):
    about = About.objects.all()

    return render(request, 'core/about.html', {
        'about':about
    })
def roll(request):
    r = random.randint(1, 7)

    return render(request,'core/roll.html',{
        'r':r,
    })

core/templates/core/about.html
{% extends 'core/base.html' %}

{% block title %}About{% endblock %}
{% block content %}




<div class="mb-36 px-6 py-4 bg-black rounded-xl">

    {% for topic in about %}
        {% if topic.visible %}

            <div class="mb-16 px-6 py-4 bg-black rounded-xl">
                <a href="/">
                <img src="{{ topic.image.url }}" class=" object-fill rounded-t-xl">
                </a>
            </div>
                <h2 class="mb-6 text-2xl text-center text-yellow-500">About</h2>

                    <p class="text-sm text-center text-white hover:text-gray-500"><i>{{ topic.about }}</i></p>

        {% endif %}
    {% endfor %}

</div>


{% endblock %}

core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"></script>

        <title>{% block title %}{% endblock %} | Circuit Bored</title>
    </head>

    <body class="bg-auto bg-black flex-col min-h-screen">

  </div>
        <nav class="relative flex w-full flex-nowrap py-2 px-2 flex justify-between bg-green-900 items-center border-b border-gray-200">
            <div class="grid grid-cols-2">
            <a href="{% url 'browse:index' %}">
                <img src="https://raw.githubusercontent.com/enzosupreme/cbl-images/main/logo.png"
                class="flex object-scale-down h-20 w-40"/>
                </a>

                <div class="py-6 bg-green-900 rounded-xl mb-18 text-2xl text-white hover:text-yellow-500">

                <a href="/">
                    Circuit Bored
                </a>
            </div>
            </div>
            <div class="lg:hidden"></div>
            <ul class="hidden md:flex float-right mr-10 md:flex leading-[80px] space x-3">
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'browse:index' %}" class="text-sm md:text-md lg:text-lg font-semibold text-yellow-500 hover:text-white">Projects</a>
                </li>
                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'core:commission' %}" class="text-sm md:text-md lg:text-lg font-semibold text-yellow-500 hover:text-white">Commission</a>
                </li>

                <button class="text-sm sm:text-md lg:text-lg text-yellow-500 hover:bg-white hover:text-white rounded-xl px-6">
                    <a href="https://circuitboredlab.etsy.com">
                    Shop</a>
                </button>

                <li class="mx-4 my-6 md:my-0">
                    <a href="{% url 'core:about' %}" class="text-sm md:text-md lg:text-lg font-semibold text-yellow-500 hover:text-white">About</a>
                </li>


            </ul>
            </div>
                <button id="hamburger-menu" class="lg:hidden text-yellow-500 p-2">
                     <a href="{% url 'core:menu' %}">
                    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path></svg>
                   </a>
                </button>

        </nav>

        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="flex w-full mx-auto max-w-screen-2xl md:flex md:items-center md:justify-between pl-20 fixed bottom-0 z-50 py-2 bg-purple-900">

        <ul class="flex flex-wrap items-center mt-3 text-sm font-medium text-gray-500 dark:text-gray-400">

        <li>
        <a href="{% url 'core:about' %}" ><img src="https://raw.githubusercontent.com/enzosupreme/cbl-images/main/logo.png"
                class="flex object-scale-down h-5 w-5 pr-2"/></a>
        </li>
        <li>
            <a href="https://github.com/enzosupreme" class="mr-4 hover:underline md:mr-6 text-white">Github</a>
        </li>
        <li>
            <a href="https://www.instagram.com/circuitboredlab/" class="mr-4 hover:underline md:mr-6 text-white ">Instagram</a>
        </li>
        <li>
            <a href="https://x.com/CircuitBoredLab?t=5E3CiOdZE1bWFomF7Cq2Tw&s=09" class="mr-4 hover:underline md:mr-6 text-white">Twitter | X</a>
        </li>

    </ul>

        </footer>

    </body>



</html>

core/templates/core/commission.html
{% extends 'core/base.html' %}

{% block title %}Commission{% endblock %}
{% block content %}

<div class="mt-6 px-6 py-4 bg-black rounded-xl">
        <h2 class="mb-6 text-2xl text-center text-yellow-500">Services</h2>

        <div class="mb-20 grid grid-cols-1 gap-3">
            {% for service in services %}
            <div>
                    <div class="p-12 bg-green-900 hover:bg-green-700 rounded-xl">
                        <a href="{% url 'core:services' %}">
                            <h2 class="text-2xl text-center text-white hover:text-yellow-500">{{ service.name }}</h2>
                            <h1 class="text-xs py-3 text-center text-yellow-600"><i>{{ service.about }}</i></h1>

                        </a>

                    </div>

            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Welcome{% endblock %}
{% block content %}
    <div class="px-6 py-6 bg-black mb-3">
        <h2 class="text-2xl pr-6 text-center text-yellow-700">
            <i>
                'All you need is the <span class="text-red-700">desire</span> to

                'make <span class="text-green-700">beautiful things</span> happen'
            </i>
        </h2>
        </div>
        <div class="px-1 py-1 bg-black mb-8 text-2xl pr-6 text-center text-white">
            <i>
                -Bob Ross
            </i>
        </div>
    <a href="{% url 'browse:index' %}">

    </a>
    <div class="px-6 py-10 bg-black rounded-xl">
        <h2 class="mb-8 text-2xl pr-6 text-center text-purple-900 hover:text-white">Stuff I Made</h2>

        <form method="get" action="{% url 'browse:index' %}">
            </form>

        <div class="grid grid-cols-2 gap-3">
            {% for project in projects %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>
                        <img src="{{ project.image.url }}" class=" object-fill rounded-t-xl">
                    </div>

                    <div class="p-3 bg-purple-900 rounded-b-xl">
                        <h2 class="text-sm sm:text-md lg:text-lg text-white">{{ project.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="mt-6 mb-20 px-6 py-4 bg-black rounded-xl">
        <h2 class="mb-12 text-sm sm:text-md lg:text-lg text-center text-white hover:text-purple-700">Categories</h2>

        <div class="grid grid-cols-3 gap-3">
            {% for category in categories %}
            <div>
                    <div class="p-3 bg-green-900 rounded-xl">
                        <a href="{% url 'browse:index' %}?query={{ query }}&category={{ category.id }}">
                            <h2 class="text-xs sm:text-s lg:text-lg xl:text-xl text-white hover:text-yellow-700">{{ category.name }}</h2>
                            <p class=" text-xs sm:text-s lg:text-lg xl:text-xl text-yellow-700"> {{ category.projects.count }} projects</p>

                        </a>

                    </div>

            </div>
            {% endfor %}
        </div>

        <div class="py-3 mt-n4 mb-3 bg-black rounded-xl">
        <a href="{% url 'browse:shangri-la' %}">
        <h2 class="text-2xl text-center text-black hover:text-green-700">
                Circuit Bored Garden
        </h2>
        </a>
        </div>

        <div class="flex w-full justify-center items-center">
            <a href="{% url 'terrarium:terrariums' %}">
                <img src="https://raw.githubusercontent.com/enzosupreme/cbl-images/main/logo.png"
                class="flex object-scale-down h-20 w-40"/>
                </a>
        </div>

    </div>
{% endblock %}

core/templates/core/menu.html
{% extends 'core/base.html' %}

{% block title %}Menu{% endblock %}
{% block content %}

<div class="mt-6 px-6 py-4 bg-black rounded-xl">
        <h2 class="mb-6 text-2xl text-center text-yellow-500">Menu</h2>

        <div class="mb-20 grid grid-cols-1 gap-3">
            {% for item in menu_items %}
            <div>
                    <div class="p-12 bg-green-900 hover:bg-green-700 rounded-xl">
                        <a href="{{ item.link }}">
                            <h2 class="text-2xl text-center text-white hover:text-yellow-700">{{ item.name }}</h2>

                        </a>

                    </div>

            </div>
            {% endfor %}
        </div>

    </div>
{% endblock %}

core/templates/core/roll.html
{% extends 'core/base.html' %}

{% block title %}Dice roll{% endblock %}


{% block content %}

    <div class="mb-20 px-6 py-12 bg-black rounded-xl">
      <a href="/">
        <h3 class="text-white bg-red text-2xl rounded-xl text-center">{{ r }}</h3>
      </a>


    </div>

{% endblock %}

core/templates/core/servicerequest.html
<h2> Service request submission</h2>

<p><b>Subject: </b>{{ subject }}</p>
<p><b>E-mail:</b>{{ email }}</p>
<p><b>Message:</b>{{ message }}</p>

core/templates/core/services.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}


{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="POST" action=".">
    {% csrf_token %}
    <div class="space-y-4 px-6 text-black bg-gray-200 rounded-xl">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_field.errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
        {% for field in form %}
            {{ field.errors }}
        {% endfor %}

        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <button class="mt-4 py-4 px-8 text-lg bg-white hover:bg-red-900 rounded-xl">Send</button>
</form>
{% endblock %}