CBL/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('browse/', include('browse.urls')),
    path('dnd/', include('dnd.urls')),
    path('terrarium/', include('terrarium.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import LoginForm



app_name = 'browse'

urlpatterns = [
    path('', views.index, name='index'),
    path('shangri-la/',views.garden,name='shangri-la'),
    path('<int:pk>/', views.image, name='images'),
    path('thermo/',views.thermo, name='thermo'),
    path('santa/',views.santa, name='santas'),
    path('ticket/', views.gift, name='gifts'),
    path('signup/',views.signup,name='signup'),
    path('login/',auth_views.LoginView.as_view(template_name='browse/login.html',authentication_form=LoginForm), name='login'),
]

projects/urls.py
from django.urls import path, include

from . import views

app_name = 'projects'

urlpatterns = [
    path('', views.projects, name='projects'),
    path('browse/', include('browse.urls')),
    path('new/', views.new, name='new'),
    path('<int:pk>/images/', views.images, name='images'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/enchance/', views.enhance, name='enhance'),
]

browse/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Key(models.Model):
    adafruit_username = models.CharField(max_length=75)
    adafruit_key = models.CharField(max_length=75)

class Santa(models.Model):
    name = models.CharField(max_length=75)
    def __str__(self):
        return self.name



class Gifter(models.Model):

    number = models.IntegerField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='numbers', on_delete=models.CASCADE, null=True)

browse/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from .models import Santa, Gifter

INPUT_CLASSES = 'w-full py-4 px-6 rounded-xl border'
class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Enter Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your Username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Create Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Confirm Password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

class SecretSanta(forms.ModelForm):
    class Meta:
        model = Gifter
        fields = ('number',)

        number = forms.CharField(widget= forms.IntegerField())

browse/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Q
#from adafruit_IO import Client,MQTTClient,Feed
from .models import Santa, Gifter
from .forms import SignupForm, SecretSanta
import random
from projects.models import Project, Category, About, Garden_Pic

#username = 'your_adafruit_io_username'
#key = 'your_adafruit_io_key'

#aio = adafruitIO(username, key)
#feed_id = feed['thermo']

def index(request):
    query = request.GET.get('query', '')
    category_id = request.GET.get('category', 0)
    projects = Project.objects.filter(invisible=False)
    categories = Category.objects.all()

    if category_id:
        projects = projects.filter(category_id=category_id)
    if query:
        projects = projects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'browse/index.html', {
        'projects': projects,
        'query': query,
        'categories': categories,
        'category_id': int(category_id),
    })

def projects(request):
    query = request.GET.get('query', projects.category)
    category_id = request.GET('category', 0)
    projects = Project.object.filter(invisible=False)
    categories = Category.objects.all()

    if category_id:
        projects = projects.filter(category_id=category_id)

    if query:
        projects = projects.filter(Q(name__icontains=query) | Q(description__icontains=query))
    return render(request, 'browse/index.html', {
        'projects': projects,
        'query':query,
        'categories':categories,
        'category_id': int(category_id)
    })
def garden(request):
    images = Garden_Pic.objects.all()

    return render(request, 'browse/shangri-la.html', {
        'images':images,
    })

def image(request, pk):
    images = get_object_or_404(Garden_Pic, pk=pk)

    return render(request, 'browse/images.html', {
        'images': images,
    })
@login_required
def thermo(request):

    return render(request, 'browse/thermo.html', {
        #'images':images,
    })
@login_required
def santa(request):
    gifts = Gifter.objects.filter(created_by=request.user)
    santas = Santa.objects.all()
    #r = random.randint(0,(len(gifts)-1))

    secret_santa = gifts[0].number
    ss = santas[secret_santa-1]

    return render(request, 'browse/santa.html', {
        'gifts': gifts,
        'secret_santa': secret_santa,
        'ss':ss,
    })

def signup(request):
    if request.method =='POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/browse/login/')
    else:
        form = SignupForm()

    return render(request, 'browse/signup.html', {

        'form': form,
    })
@login_required
def gift(request):

    if request.method == 'POST':
        form = SecretSanta(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.created_by = request.user
            post.save()

            return redirect('/browse/santa')
    else:
        form = SecretSanta()


    return render(request,'browse/ticket.html', {
        'form': form,
    })

browse/templates/browse/category.html
{% extends 'core/base.html' %}

{% block title %}{{ category.name }}{% endblock %}
{% block content %}
    <div class="mt-6 px-6 py-12 bg-green-900 rounded-xl">
        <a href="/">
        <h2 class="mb-12 text-2xl pr-10 text-center text-yellow-500">{{ category.name }}</h2>
        </a>
        <form method="get" action="{%url 'browse:index' %}"></form>
        <div class="grid grid-cols-3 gap-3">
            {% for project in category %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>
                        <img src="{{ project.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-6 bg-yellow-600 rounded-b-xl">
                        <h2 class="text-2xl text-white">{{ project.name }}</h2>
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

browse/templates/browse/images.html
{% extends 'core/base.html' %}

{% block title %}Garden Pic{% endblock %}

{% block content %}

    <div class="p-6 bg-black rounded-xl">
        <div class=" grid h-100 w-100 gap-6 p-3 ">

        <a href="{% url 'browse:shangri-la' %}">

            <div class="col-span-3 rounded-xl touch-pinch-zoom">
            <img src="{{ images.image.url }}" class="mb-8 rounded-xl">
            </div>
        </a>

        </div>
    </div>

{% endblock %}

browse/templates/browse/index.html
{% extends 'core/base.html' %}

{% block title %}Projects{% endblock %}
{% block content %}
    <div class="grid grid-cols-6">
        {% for category in categories %}
                <h1 class="mb-6 px-2 text-xs sm:text-sm lg:text-lg xl:text-xl text-center text-white hover:text-yellow-900{% if category.id == category_id %} text-yellow-500{% endif %}">
                    <a href="{% url 'browse:index' %}?query={{ query }}&category={{ category.id }}">{{ category.name }}</a>
                </h1>

        {% endfor %}
    </div>

    <div class="mt-2 mb-20 px-3 py-12 bg-black-rounded-xl">

        <div class="grid grid-cols-2 gap-3">
            {% for project in projects %}
            <div>
                <a href="{% url 'projects:detail' project.id %}">
                    <div>
                        <img src="{{ project.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-3 bg-green-900 rounded-b-xl">

                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ project.name }}
                            <a href="{% url 'projects:images' project.id %}" ></a>
                        </h2>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>


{% endblock %}

browse/templates/browse/login.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log In</h1>

    <form method="POST" action=".">
        {% csrf_token %}



        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password }}
        </div>


        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-green-700 hover-bg-green-900 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}

browse/templates/browse/santa.html
{% extends 'core/base.html' %}

{% block title %}Secret Santa{% endblock %}


{% block content %}

    <div class="mb-20 px-6 py-12 bg-black rounded-xl">
      <a href="/">
        <h2 class="mb-12 text-2xl sm:text-md lg:text-lg xl:text-xl text-center text-white">Price limit: $200</h2>
        <h2 class="mb-12 text-2xl sm:text-md lg:text-lg xl:text-xl text-center text-white">Prepare a gift for:</h2>
      </a>
        <h3 class="text-white bg-red text-2xl rounded-xl text-center">{{ ss }}</h3>

    </div>

{% endblock %}

browse/templates/browse/shangri-la.html
{% extends 'core/base.html' %}

{% block title %}Shangri-la{% endblock %}

{% block content %}

        <div class="grid grid-cols-5 gap-3 mb-20">
            {% for image in images %}
            <div>
                <a href="{% url 'browse:images' image.id %}">
                    <div>
                        <img src="{{ image.image.url }}" class="rounded-xl w-50 h-50">
                    </div>
                </a>
            </div>
            {% endfor %}
        </div>


{% endblock %}

browse/templates/browse/signup.html
{% extends 'core/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="POST" action=".">
        {% csrf_token %}



        <div class="mb-3">
            <label class="inline-block mb-2">Username</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label><br>
            {{ form.password1 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Confirm Password</label><br>
            {{ form.password2 }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Secret Santa Number</label><br>
            {{ form.number }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-4 px-8 text-lg bg-green-700 hover-bg-green-900 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}

browse/templates/browse/thermo.html
{% extends 'core/base.html' %}

{% block title %}Thermo Controller{% endblock %}
{% block content %}




<div class=" grid grid-cols-2 mt-36 mb-36 px-6 py-4 bg-black rounded-xl items-center gap-2">

    <button class="px-3 py-3 bg-blue-400 text-xl text-white hover:text-yellow-500 rounded-xl">
      <h1>COLD</h1>
    </button>

    <button class="px-3 py-3 bg-red-500 text-xl text-white hover:text-yellow-500 rounded-xl">
      <h1>HEAT</h1>
    </button>


</div>


{% endblock %}

browse/templates/browse/ticket.html
{% extends 'core/base.html' %}

{% block title %}Secret Santa{% endblock %}
{% block content %}

<div class="w-1/2 my-6 p-6 mx-auto bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Ticket</h1>

    <form method="POST" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Ticket Number</label><br>
            {{ form.number }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class="py-4 px-8 text-lg bg-green-700 hover-bg-green-900 rounded-xl text-white">Submit</button>
    </form>
</div>

{% endblock %}