CBL/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('core.urls')),
    path('projects/', include('projects.urls')),
    path('browse/', include('browse.urls')),
    path('dnd/', include('dnd.urls')),
    path('terrarium/', include('terrarium.urls')),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

terrarium/urls.py
from django.urls import path, include

from . import views

app_name = 'terrarium'

urlpatterns = [
    path('terrarium/', views.terrariums, name='terrariums'),
    path('terrarium/<int:pk>/', views.detail, name='detail'),
    path('plant/<int:pk>/', views.plant_detail, name='plant'),
    path('plants/',views.plants, name='plants')

]

terrarium/models.py
from django.db import models

class Plant(models.Model):
    name = models.CharField(max_length=2555)
    description = models.TextField(blank=True, null=True)
    image = models.ImageField(upload_to='plant_images', blank=True, null=True)
    link = models.URLField(max_length=200, blank=True, null=True)


    def __str__(self):
        return self.name

class Terrarium(models.Model):
    name = models.CharField(max_length=2555)
    image = models.ImageField(upload_to='terrarium_images', blank=True, null=True)
    plant1 = models.ForeignKey(Plant, related_name='plant', on_delete=models.CASCADE)
    plant2 = models.ForeignKey(Plant, related_name='plant2', on_delete=models.CASCADE)
    plant3 = models.ForeignKey(Plant, related_name='plant3', on_delete=models.CASCADE, blank=True, null=True)
    plant4 = models.ForeignKey(Plant, related_name='plant4', on_delete=models.CASCADE, blank=True, null=True)



    def __str__(self):
        return self.name

terrarium/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from .models import Plant,Terrarium



def plants(request):
    plants = Plant.objects.all()

    return render(request, 'terrarium/plants.html', {
        'plants': plants,

    })

def terrariums(request):
    terrariums = Terrarium.objects.all()

    return render(request, 'terrarium/terrarium.html', {
        'terrariums': terrariums
    })

def detail(request, pk):
    habitats = get_object_or_404(Terrarium, pk=pk)

    return render(request, 'terrarium/detail.html', {
        'habitats': habitats,

    })

def plant_detail(request, pk):
    plant = get_object_or_404(Plant, pk=pk)

    return render(request, 'terrarium/plant_detail.html', {
        'plant': plant,

    })

terrarium/templates/terrarium/detail.html
{% extends 'core/base.html' %}

{% block title %}{{ terrarium.name }}{% endblock %}

{% block content %}

    <div class="justify-center p-6 bg-black rounded-xl">
        <div class=" grid h-100 w-100 gap-6 p-3">

        <a href="{% url 'terrarium:terrariums' %}">
        <h1 class="mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 hover:text-yellow-700">{{ habitats.name }}</h1></a>

            <div class="grid grid-cols-2">
                <a href="{{ habitats.plant1.link}} ">
                <img src="{{ habitats.plant1.image.url }}" class=" justify-center cols-span-2 pr-3 mb-8 rounded-xl">
                <h1 class="mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 hover:text-yellow-700">{{ habitats.plant1.name }}</h1></a>

                </a>
                <a href="{{ habitats.plant2.link}} ">
                <img src="{{ habitats.plant2.image.url }}" class=" justify-center cols-span-1 pr-3 mb-8 rounded-xl">
                <h1 class="mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 hover:text-yellow-700">{{ habitats.plant2.name }}</h1>
                </a>

                <a href="{{ habitats.plant3.link}} ">
                <img src="{{ habitats.plant3.image.url }}" class=" justify-center cols-span-1 pr-3 mb-8 rounded-xl">
                <h1 class="mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 hover:text-yellow-700">{{ habitats.plant3.name }}</h1>
                </a>

                <a href="{{ habitats.plant4.link}} ">
                <img src="{{ habitats.plant4.image.url }}" class=" justify-center cols-span-1 pr-3 mb-8 rounded-xl">
                <h1 class="mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center text-yellow-500 hover:text-yellow-700">{{ habitats.plant4.name }}</h1>
                </a>


            </div>


        </div>
    </div>


{% endblock %}

terrarium/templates/terrarium/plant_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ plant.name }}{% endblock %}

{% block content %}

    <div class=" grid grid-cols-1 justify-center p-6 bg-green-900 rounded-xl">

        <a href="{% url 'terrarium:terrariums' %}">

            <div class="grid grid-cols-1">

                <h1 class=" col-span-2 mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center bg-green-900 text-yellow-500 hover:text-yellow-700">{{ plant.name }}</h1>
                <br></br>
                <img src="{{ plant.image.url }}" class=" justify-center cols-span-1 pr-3 mb-8 rounded-xl">
                <h1 class=" col-span-2 mb-6 text-xs sm:text-md lg:text-lg xl:text-xl text-center bg-green-900 text-white hover:text-yellow-700">{{ plant.description }}</h1>

        </div>
        </a>

    </div>

{% endblock %}

terrarium/templates/terrarium/plants.html
{% extends 'core/base.html' %}

{% block title %}Plants{% endblock %}
{% block content %}


    <div class="mt-2 mb-20 px-3 py-12 bg-black rounded-xl">

        <div class="grid grid-cols-2 gap-3">
            {% for plant in plants %}
            <div>
                <a href="{% url 'terrarium:plant' plant.id %}">
                    <div>
                        <img src="{{ plant.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-3 bg-green-900 rounded-b-xl">

                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ plant.name }}

                        </h2>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}

terrarium/templates/terrarium/terrarium.html
{% extends 'core/base.html' %}

{% block title %}Terrariums{% endblock %}
{% block content %}


    <div class="mt-2 mb-20 px-3 py-12 bg-black rounded-xl">

        <div class="grid grid-cols-2 gap-3">
            {% for terrarium in terrariums %}
            <div>
                <a href="{% url 'terrarium:detail' terrarium.id %}">
                    <div>
                        <img src="{{ terrarium.image.url }}" class="object-contain rounded-t-xl">
                    </div>

                    <div class="p-3 bg-green-900 rounded-b-xl">

                        <h2 class="text-sm sm:text-sm lg:text-lg xl:text-xl text-yellow-600 hover:text-white">{{ terrarium.name }}

                        </h2>

                    </div>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}